{% set name = "visions" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47bbceb9d6efe931120ef2dff871e4df9591380abb25cae9c23f9a1dfb1dd20f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs >=19.3.0
    - networkx >=2.4
    - numpy
    - pandas >=0.25.3
    - python >=3.6
    - tangled-up-in-unicode >=0.0.4
    - bottleneck
    - multimethod 1.4

test:
  imports:
    - visions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dylan-profiler/visions
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Visions provides an extensible suite of tools to support common data analysis operations including 
    type inference on unknown data, casting data types and automated data summarization.
  doc_url: https://dylan-profiler.github.io/visions/
  dev_url: https://github.com/dylan-profiler/visions

extra:
  recipe-maintainers:
    - philip-khor
